# Top-10 meta decklists (TEF-CRI), fetched from limitlesstcg.
# Each entry: (count, card_name). Category headers are implicit; resolver matches by name.
DECKS = {
"Dragapult ex": [
    (4,"Dreepy"),(4,"Drakloak"),(3,"Dragapult ex"),(2,"Munkidori"),(1,"Dunsparce"),
    (1,"Dudunsparce"),(1,"Budew"),(1,"Fezandipiti ex"),(1,"Meowth ex"),
    (4,"Lillie's Determination"),(3,"Boss's Orders"),(2,"Crispin"),(1,"Rosa's Encouragement"),
    (4,"Buddy-Buddy Poffin"),(4,"Poke Pad"),(4,"Ultra Ball"),(4,"Crushing Hammer"),
    (3,"Night Stretcher"),(1,"Special Red Card"),(1,"Unfair Stamp"),(2,"Risky Ruins"),
    (4,"Psychic Energy"),(3,"Fire Energy"),(2,"Darkness Energy"),
],
"N's Zoroark ex": [
    (4,"N's Zorua"),(4,"N's Zoroark ex"),(2,"N's Zekrom"),(1,"N's Darumaka"),(1,"N's Darmanitan"),
    (1,"Tatsugiri"),(1,"Budew"),(1,"Yveltal"),(1,"Munkidori"),(1,"Pecharunt ex"),
    (1,"Fezandipiti ex"),(1,"Meowth ex"),
    (4,"Lillie's Determination"),(3,"Boss's Orders"),(2,"Cyrano"),(1,"Black Belt's Training"),
    (1,"Ruffian"),(4,"Buddy-Buddy Poffin"),(4,"Transformation Tome"),(3,"Ultra Ball"),
    (3,"N's PP Up"),(2,"Night Stretcher"),(1,"Poke Pad"),(1,"Special Red Card"),(1,"Secret Box"),
    (2,"Binding Mochi"),(2,"N's Castle"),
    (7,"Darkness Energy"),
],
"Crustle": [
    (4,"Mega Kangaskhan ex"),(3,"Dwebble"),(3,"Crustle"),(1,"Team Rocket's Articuno"),
    (1,"Team Rocket's Kangaskhan ex"),
    (4,"Lillie's Determination"),(4,"Boss's Orders"),(4,"Team Rocket's Petrel"),(2,"Hilda"),
    (1,"Xerosic's Machinations"),(1,"Brock's Scouting"),(1,"Bianca's Devotion"),(1,"Eri"),
    (4,"Crushing Hammer"),(4,"Jumbo Ice Cream"),(3,"Pokegear 3.0"),(2,"Buddy-Buddy Poffin"),
    (1,"Switch"),(1,"Ultra Ball"),(1,"Hero's Cape"),(1,"Team Rocket's Factory"),
    (4,"Mist Energy"),(4,"Growing Grass Energy"),(4,"Spiky Energy"),(1,"Water Energy"),
],
"Slowking": [
    (4,"Slowpoke"),(3,"Slowking"),(2,"Latias ex"),(2,"Meowth ex"),(2,"Kyurem"),
    (1,"Fezandipiti ex"),(1,"Lillie's Clefairy ex"),(1,"Annihilape"),(1,"Budew"),
    (1,"Metagross"),(1,"Smoochum"),
    (4,"Lillie's Determination"),(3,"Ciphermaniac's Codebreaking"),(1,"Carmine"),(1,"Dawn"),
    (1,"Hilda"),(1,"Colress's Tenacity"),(1,"Surfer"),(4,"Ultra Ball"),(4,"Poke Pad"),
    (3,"Night Stretcher"),(3,"Wondrous Patch"),(1,"Max Rod"),(4,"Academy at Night"),
    (4,"Telepathic Psychic Energy"),(4,"Psychic Energy"),(2,"Boomerang Energy"),
],
"Hydrapple ex": [
    (2,"Chikorita"),(2,"Bayleef"),(2,"Meganium"),(1,"Mega Meganium ex"),(2,"Applin"),
    (2,"Dipplin"),(2,"Hydrapple ex"),(2,"Teal Mask Ogerpon ex"),(1,"Shuckle"),
    (4,"Lillie's Determination"),(2,"Xerosic's Machinations"),(2,"Drayton"),(2,"Dawn"),
    (1,"Rosa's Encouragement"),(4,"Bug Catching Set"),(2,"Rare Candy"),(2,"Night Stretcher"),
    (2,"Repel"),(1,"Buddy-Buddy Poffin"),(2,"Festival Grounds"),(2,"Forest of Vitality"),
    (13,"Grass Energy"),(4,"Growing Grass Energy"),(1,"Legacy Energy"),
],
"Alakazam": [
    (4,"Swinub"),(2,"Piloswine"),(3,"Mamoswine ex"),(2,"Abra"),(1,"Abra"),(3,"Kadabra"),
    (3,"Alakazam"),(2,"Torchic"),(1,"Combusken"),(2,"Blaziken ex"),(1,"Fezandipiti ex"),
    (1,"Klinklang"),
    (3,"Lillie's Determination"),(2,"Hilda"),(2,"Boss's Orders"),(1,"Ciphermaniac's Codebreaking"),
    (1,"Crispin"),(4,"Buddy-Buddy Poffin"),(4,"Rare Candy"),(2,"Night Stretcher"),(2,"Poke Pad"),
    (1,"Switch"),(1,"Ultra Ball"),(1,"Special Red Card"),(2,"Battle Cage"),
    (5,"Fighting Energy"),(1,"Rocky Fighting Energy"),(1,"Fire Energy"),(1,"Legacy Energy"),
    (1,"Psychic Energy"),
],
"Raging Bolt ex": [
    (3,"Mega Kangaskhan ex"),(3,"Teal Mask Ogerpon ex"),(3,"Meowth ex"),(2,"Raging Bolt ex"),
    (2,"Latias ex"),(1,"Chien-Pao"),(1,"Passimian"),(1,"Fezandipiti ex"),
    (1,"Wellspring Mask Ogerpon ex"),(1,"Lillie's Clefairy ex"),
    (4,"Crispin"),(2,"Boss's Orders"),(2,"Cyrano"),(1,"Ciphermaniac's Codebreaking"),
    (4,"Ultra Ball"),(4,"Energy Switch"),(2,"Night Stretcher"),(2,"Glass Trumpet"),
    (1,"Prime Catcher"),(1,"Special Red Card"),(4,"Area Zero Underdepths"),
    (8,"Grass Energy"),(2,"Lightning Energy"),(2,"Fighting Energy"),(2,"Psychic Energy"),
    (1,"Water Energy"),
],
"Ogerpon Box": [
    (3,"Meowth ex"),(2,"Mega Kangaskhan ex"),(2,"Lillie's Clefairy ex"),(2,"Munkidori"),
    (2,"Latias ex"),(1,"Psyduck"),(1,"Wellspring Mask Ogerpon ex"),(1,"Teal Mask Ogerpon ex"),
    (1,"Pecharunt"),(1,"Iron Leaves ex"),(1,"Team Rocket's Mimikyu"),(1,"Passimian"),
    (1,"Chien-Pao"),(1,"Moltres"),(1,"Fezandipiti ex"),
    (4,"Crispin"),(3,"Boss's Orders"),(3,"Cyrano"),(1,"Brock's Scouting"),
    (1,"Ciphermaniac's Codebreaking"),(4,"Ultra Ball"),(3,"Energy Switch"),(2,"Night Stretcher"),
    (1,"Unfair Stamp"),(4,"Area Zero Underdepths"),
    (3,"Grass Energy"),(3,"Prism Energy"),(2,"Darkness Energy"),(2,"Psychic Energy"),
    (1,"Fighting Energy"),(1,"Water Energy"),(1,"Fire Energy"),
],
"Lillie's Clefairy ex": [
    (4,"Meowth ex"),(4,"Mega Kangaskhan ex"),(4,"Lillie's Clefairy ex"),(3,"Latias ex"),
    (2,"Fezandipiti ex"),(2,"Wellspring Mask Ogerpon ex"),(1,"Koraidon ex"),(1,"Chien-Pao"),
    (1,"Moltres"),(1,"Tapu Koko ex"),
    (3,"Crispin"),(3,"Boss's Orders"),(2,"Ciphermaniac's Codebreaking"),(1,"Cyrano"),
    (4,"Dusk Ball"),(4,"Ultra Ball"),(3,"Wondrous Patch"),(1,"Prime Catcher"),
    (2,"Lillie's Pearl"),(3,"Area Zero Underdepths"),(1,"Prism Tower"),
    (4,"Psychic Energy"),(2,"Fire Energy"),(1,"Fighting Energy"),(1,"Water Energy"),
    (1,"Telepathic Psychic Energy"),(1,"Lightning Energy"),
],
"Rocket's Honchkrow": [
    (4,"Team Rocket's Murkrow"),(3,"Team Rocket's Honchkrow"),(2,"Team Rocket's Porygon"),
    (1,"Team Rocket's Porygon2"),(2,"Team Rocket's Articuno"),
    (4,"Team Rocket's Proton"),(4,"Team Rocket's Ariana"),(4,"Team Rocket's Giovanni"),
    (4,"Team Rocket's Petrel"),(4,"Team Rocket's Archer"),(4,"Poke Pad"),(4,"Roto-Stick"),
    (4,"Team Rocket's Transceiver"),(3,"Night Stretcher"),(1,"Miracle Headset"),
    (1,"Air Balloon"),(3,"Team Rocket's Factory"),
    (4,"Team Rocket's Energy"),(4,"Ignition Energy"),
],
}
